### ISSUE TITLE
Post titles are no longer links from the home page

### ISSUE THREAD

**Issue by loganmarchione** [MachoThemes/decode#102]
Not sure if this is really an "issue", but I noticed it in a recent update.  
From my [homepage](https://loganmarchione.com/), all my post titles are no longer links. Users are required to click "Read more..." to get to the post. However, on the [search page](https://loganmarchione.com/?s=test), the post title are still links. Is there a way to make the post titles on the homepage into links (like on the search page)?

**Comment by cristianraiber** [comment]
@robciucioan Please handle this.
