### ISSUE TITLE
Show Navigation Menu doesn't work in 3.14.0

### ISSUE THREAD

**Issue by 13xforever** [MachoThemes/decode#104]
There's no navigation menu anymore after updating to 3.13.0. That toggle in the settings does nothing. It is also not localized now.

**Comment by cristianraiber** [comment]
Hey @13xforever - latest version is 3.14.0 - https://downloads.wordpress.org/theme/decode.3.14.0.zip 

Could you try this one and let us know if it's still happening ?

Thanks.

**Comment by 13xforever** [comment]
I'm rolling back atm

**Comment by 13xforever** [comment]
I rolled back. It happened after updating 3.13.0 to 3.14.0. I've updated the bug.

**Comment by 13xforever** [comment]
More info if it matters:
- WordPress 4.5.2–ru_RU
- PHP 5.5.9
- MySQL 5.5.49

**Comment by cristianraiber** [comment]
Ok, thanks for this. We'll look into it and release an update as soon as possible.

**Comment by cristianraiber** [comment]
Hi @13xforever - should be fixed now with v 3.14.1 (update should be already showing up in your DashboarD). Thanks!
