### ISSUE TITLE
Updating to Version 3.14.7 results in blank page

### ISSUE THREAD

**Issue by todestoast** [MachoThemes/decode#109]
**Bug:** After I updated the theme to version 3.14.7 my complete site went blank

**How to reproduce:** Update the theme via the wordpress update page.

**Log output:**[Tue Jul 05 23:49:50 2016] [warn] [client xxxx] mod_fcgid: stderr: PHP Warning:  require(/var/www/wp-content/themes/decode/inc/tgm-plugin-activation/tgm-plugin-activation.php): failed to open stream: No such file or directory in /var/www/wp-content/themes/decode/functions.php on line 183
[Tue Jul 05 23:49:50 2016] [warn] [client xxxx] mod_fcgid: stderr: PHP Fatal error:  require(): Failed opening required '/var/www/wp-content/themes/decode/inc/tgm-plugin-activation/tgm-plugin-activation.php' (include_path='/var/www/wp-content/plugins/podlove-podcasting-plugin-for-wordpress/vendor/pear/pear_exception:.:/package/host/localhost/php-5.5.9/lib/php') in /var/www/wp-content/themes/decode/functions.php on line 183
[Tue Jul 05 23:50:03 2016] [warn] [client xxxx] mod_fcgid: stderr: PHP Warning:  require(/var/www/wp-content/themes/decode/inc/tgm-plugin-activation/tgm-plugin-activation.php): failed to open stream: No such file or directory in /var/www/wp-content/themes/decode/functions.php on line 183
[Tue Jul 05 23:50:03 2016] [warn] [client xxxx] mod_fcgid: stderr: PHP Fatal error:  require(): Failed opening required '/var/www/wp-content/themes/decode/inc/tgm-plugin-activation/tgm-plugin-activation.php' (include_path='/var/www/wp-content/plugins/podlove-podcasting-plugin-for-wordpress/vendor/pear/pear_exception:.:/package/host/localhost/php-5.5.9/lib/php') in /var/www/wp-content/themes/decode/functions.php on line 183
[Tue Jul 05 23:50:04 2016] [warn] [client xxxx] mod_fcgid: stderr: PHP Warning:  require(/var/www/wp-content/themes/decode/inc/tgm-plugin-activation/tgm-plugin-activation.php): failed to open stream: No such file or directory in /var/www/wp-content/themes/decode/functions.php on line 183
[Tue Jul 05 23:50:04 2016] [warn] [client xxxx] mod_fcgid: stderr: PHP Fatal error:  require(): Failed opening required '/var/www/wp-content/themes/decode/inc/tgm-plugin-activation/tgm-plugin-activation.php' (include_path='/var/www/wp-content/plugins/podlove-podcasting-plugin-for-wordpress/vendor/pear/pear_exception:.:/package/host/localhost/php-5.5.9/lib/php') in /var/www/wp-content/themes/decode/functions.php on line 183
[Tue Jul 05 23:51:06 2016] [warn] [client xxxx mod_fcgid: stderr: PHP Warning:  require(/var/www/wp-content/themes/decode/inc/tgm-plugin-activation/tgm-plugin-activation.php): failed to open stream: No such file or directory in /var/www/wp-content/themes/decode/functions.php on line 183
[Tue Jul 05 23:51:06 2016] [warn] [client xxxx] mod_fcgid: stderr: PHP Fatal error:  require(): Failed opening required '/var/www/wp-content/themes/decode/inc/tgm-plugin-activation/tgm-plugin-activation.php' (include_path='/var/www/wp-content/plugins/podlove-podcasting-plugin-for-wordpress/vendor/pear/pear_exception:.:/package/host/localhost/php-5.5.9/lib/php') in /var/www/wp-content/themes/decode/functions.php on line 183
[Tue Jul 05 23:51:27 2016] [warn] [client xxxx] mod_fcgid: stderr: PHP Warning:  require(/var/www/wp-content/themes/decode/inc/tgm-plugin-activation/tgm-plugin-activation.php): failed to open stream: No such file or directory in /var/www/wp-content/themes/decode/functions.php on line 183
[Tue Jul 05 23:51:27 2016] [warn] [client xxxx] mod_fcgid: stderr: PHP Fatal error:  require(): Failed opening required '/var/www/wp-content/themes/decode/inc/tgm-plugin-activation/tgm-plugin-activation.php' (include_path='/var/www/wp-content/plugins/podlove-podcasting-plugin-for-wordpress/vendor/pear/pear_exception:.:/package/host/localhost/php-5.5.9/lib/php') in /var/www/wp-content/themes/decode/functions.php on line 183

**Workaround:** I replaced the content of var/www/virtual/onahrung/talkthirtyto.me/wp-content/themes/decode with the content of the zip file of the last version.

**Comment by cristianraiber** [comment]
The w.org trac system has been causing some problems lately. Will reupload tomorrow morning ASAP.

**Comment by marcelstoer** [comment]
Same on the demo page: http://www.machothemes.com/demo/#Decode

**Comment by mmajcica** [comment]
After updating I do get a 500 from WP. I restored 3.14.3 version.

**Comment by cristianraiber** [comment]
Version 3.15.1 (latest on w.org SVN) should fix these problems.
