### ISSUE TITLE
Does this repo not reflect the WordPress repo?

### ISSUE THREAD

**Issue by loganmarchione** [MachoThemes/decode#110]
I was thinking about submitting a change, but was wondering if this repo was up-to-date? It seems to be older than the WordPress Trac repo.
https://themes.trac.wordpress.org/log/decode/

Should I just submit an issue and you'll update it on the WordPress Trac, or should I submit a pull request here?

**Comment by cristianraiber** [comment]
@loganmarchione - Just updated the Git repo to the latest w.org version :) Feel free to fork away :)

**Comment by loganmarchione** [comment]
Thanks!
