### ISSUE TITLE
Too much indentation in lists

### ISSUE THREAD

**Issue by aelog** [MachoThemes/Decode#36]
After the last update, my itemized/numbered lists are too much indented, at least twice than before the update. See the following screenshot:
![space](https://cloud.githubusercontent.com/assets/7082518/6487500/d0207212-c291-11e4-860d-9617a8ea8ffb.png)

Is this maybe due to the move of the custom CSS to Jetpack?
My custom CSS is the following: https://gist.github.com/aelog/e19e4c7771348a7baccd

**Comment by ScottSmith95** [comment]
This is likely because I switched to Normalize.css. I'll reduce the spacing in the next update. :) 
Custom CSS still works, by the way, it's just deprecated and I would suggest you move it to Jetpack.

**Comment by aelog** [comment]
Any news on this?

**Comment by aelog** [comment]
I wonder if this theme is still maintained...

**Comment by aelog** [comment]
Thanks!
