### ISSUE TITLE
[Suggestion] Add PayPal donation button to the Social buttons

### ISSUE THREAD

**Issue by ET-Bent** [MachoThemes/Decode#47]
One really neat thing would be adding a PayPal donation button to the social buttons. There could be two implementations. One would be allowing the page admin add a PayPal Email that could be donated to or let the admin set a custom code that is executed (like when generating a donation button on PayPal.com). I would prefer number 2.

**Comment by loganmarchione** [comment]
This would be even easier with PayPal's new service.  
https://www.paypal.me/

**Comment by etherReal** [comment]
:+1: much as I hate PayPal this is a top idea!
