### ISSUE TITLE
AdBlockPlus blocking social icons

### ISSUE THREAD

**Issue by TheMatjaz** [MachoThemes/decode#51]
After adding your **awesome** theme to my website, I noticed that the social icons did not appear when AdBlockPlus was activated - tested on Safari and Firefox.

While doing some modifications to the page, looks like the problem is in the class name. AdBlock hates the word **_social_** apparently, since blocks the elements named as _social-links_, _social-links-container_ and _social-link_. As soon as I changed the word _social_ to something else, like _contact_, everything was fine.

Example of the blocked part:

```html
<div class="social-links">
    <div class="social-links-container">
          <a class="social-link GithubLink" href="https://github.com/TheMatjaz" target="_blank" rel="me">
          <!-- here the svg image etc. -->
```

Possible fix:

```html
<div class="contact-links">
    <div class="contact-links-container">
          <a class="contact-link GithubLink" href="https://github.com/TheMatjaz" target="_blank" rel="me">
          <!-- here the svg image etc. -->
```

Would be nice to integrate this change in the theme to globally fix the issue.

Thanks again for the awesome work!

**Comment by robciucioan** [comment]
@TheMatjaz, I have tested on my PC and works very good.

**Comment by TheMatjaz** [comment]
@robciucioan I'm sorry, I don't understand: are you saying that the fix works well or that AdBlock is not causing any issue?

**Comment by robciucioan** [comment]
@TheMatjaz, AdBlock does not cause any problem.

**Comment by cristianraiber** [comment]
@robciucioan Can this be closed ?

**Comment by robciucioan** [comment]
@cristianraiber, I not have problems with social icons when the AdBlock/ AdBlock is is activated.

**Comment by cristianraiber** [comment]
@robciucioan Let's actually go ahead and change the mark-up. The change seems minor (a few minutes, at most) and should help us avoid possible unwanted future problems.

**Comment by robciucioan** [comment]
@cristianraiber, ok.
