### ISSUE TITLE
For href html tag, support hreflang attribute by showing it to visitors

### ISSUE THREAD

**Issue by NicolasWeb** [MachoThemes/Decode#54]
For blog posts with links in a different language than the post one, I set the `hreflang` attribute (with the addon "MCE Accessible Language Change").
It would be useful if Decode could show a '[Lang]' after the link ('link [EN]')
Here is a blog that use it: [standblog.org/blog/](http://standblog.org/blog/

**Comment by robciucioan** [comment]
@NicolasWeb, this plugin works very good when I added the language on the content.

**Comment by cristianraiber** [comment]
Closing as this isn't really a bug.

**Comment by NicolasWeb** [comment]
@cristianraiber It's not a bug, it's an enhencement request.
The layout i'm looking is something similar to [this page](http://standblog.org/blog/post/2016/02/16/En-vrac-du-mardi)
The plug-in add the tag argument, but, on the theme side, nothing is shown in the UI.

**Comment by robciucioan** [comment]
@NicolasWeb, this feature will appear in the next update.
