### ISSUE TITLE
Aligning Jetpack share buttons with Comment-link

### ISSUE THREAD

**Issue by cristianraiber** [MachoThemes/Decode#68]
See: https://wordpress.org/support/topic/aligning-jetpack-share-buttons-with-comment-link

**Comment by robciucioan** [comment]
@cristianraiber, to add this feature is need to modify the HTML structure and I'm not sure if is an a good idea.

**Comment by cristianraiber** [comment]
Closing as this isn't a bug and fixing it should be left on the plugin or the user via custom CSS.
