### ISSUE TITLE
"PGP Username" social option  is misleading

### ISSUE THREAD

**Issue by alanorth** [MachoThemes/decode#82]
In the social options of the theme customization, "PGP Username" should actually be "Keybase Username."

You could also have one for PGP Key, where the user pastes the hex of his key, like `0x8cb0d0acb5cd81ec209c6cdfbd1a0e09c2f836c0` and then link to the key on a [public key server](https://sks-keyservers.net/pks/lookup?op=vindex&search=0x8cb0d0acb5cd81ec209c6cdfbd1a0e09c2f836c0). I just have [a separate page for mine](https://mjanja.ch/gpg-public-key/).

**Comment by cristianraiber** [comment]
@alanorth A pull request goes a long way, just saying :)

**Comment by alanorth** [comment]
Fair enough! Whipped one up just now, https://github.com/MachoThemes/decode/pull/83.
