### ISSUE TITLE
Add this pull request: #83

### ISSUE THREAD

**Issue by robciucioan** [MachoThemes/decode#86]
Add this pull request: #83.

**Comment by alanorth** [comment]
You guys are doing some weird stuff with this theme, and the git / GitHub workflow. So I open an issue, and you ask me to create a pull request. I write the code and create a pull request, and you guys commit my code as your own?

It's as simple as pressing the big green button on the pull request, or cherry-picking the commit from my branch in the git command line if you don't want to use GitHub workflow. What's up?

**Comment by robciucioan** [comment]
@alanorth, next time do pull request to "development" branch please.

**Comment by alanorth** [comment]
I don't REALLY care about the commit attribution, it's just a funny behavior on your part. You could have either asked me to re-do the pull request if you honestly wanted my contribution, or if you were living in "real" git land you could have simply cherry picked my commit from my branch and the closed the issue/pull request.

**Comment by cristianraiber** [comment]
@alanorth sorry about this. We're kind of new to the git workflow, so mistakes can happen on our part. Again, really sorry.

**Comment by alanorth** [comment]
:+1:
